### ISSUE TITLE
How to directly post without get for example for login

### ISSUE THREAD

**Issue by moorthi07** [2muchcoffeecom/ng2-restangular#1]
How to directly post without get for example for login

Here is my end point user/login that takes input un, pwd and returns user object

let newAccount = { "username": "pvmoorthi_jobs@yahoo.com", "password":"moorthi"};
    
    // POST /User/Login
    this.restangular.all('/users/login').post(newAccount);

**Comment by tairezzzz** [comment]
hey @moorthi07 Can you please create this issue at [ngx-restangular](https://github.com/2muchcoffeecom/ngx-restangular). Project was renamed due to Angular SemVer.
