### ISSUE TITLE
Error when using it with angular 4 and angular CLI

### ISSUE THREAD

**Issue by andrejkaurin** [2muchcoffeecom/ng2-restangular#4]
ng2-restangular: 1.0.0-beta.3
angular: 4.2.5
angular-cli: 1.0.0-beta.28.3
node: 7.4.0
os: darwin x64

ERROR in Error encountered resolving symbol values statically. Calling function 'OpaqueToken', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol CONFIG_OBJ in /Users/andrejkaurin/Apps/app1/client/node_modules/ng2-restangular/dist/esm/src/ng2-restangular.module.d.ts, resolving symbol RestangularModule.forRoot in /Users/andrejkaurin/Apps/app1/client/node_modules/ng2-restangular/dist/esm/src/ng2-restangular.module.d.ts, resolving symbol AppModule in /Users/andrejkaurin/Apps/app1/client/src/app/app.module.ts, resolving symbol AppModule in /Users/andrejkaurin/Apps/app1/client/src/app/app.module.ts

**Comment by bhushangahire** [comment]
+1

**Comment by lmarcelocc** [comment]
Any news on this?

**Comment by tairezzzz** [comment]
You should ng**x**-restangular instead of ng**2**-restangular to work with Angular 4+. Here's [Github](https://github.com/2muchcoffeecom/ngx-restangular) and [Official website](http://ngx-restangular.com)
